feat: Change search strategy and add manufacturer to query
AllSpiceIO/cofactr-cogs pull request #6
Opened 2024-05-13 23:34 UTC by jtran

Resolves #2.

2024-05-14 15:48 UTC, kdumontnu commented
I thought this [initial commit](https://test.allspice.dev/app_path/AllSpice/actions-test/commit/f90e6a542b32ef7b16f5b74af5390f806fa27563) I tested would fail, since the default manufacturer column is `Manufacturer`, but it's lower-case `manufacturer` in the `columns.json` file. It looks like because of the option type it just omits the manufacturer. I think if we're using `mpn` it should error if we can't find `bom_manufacturer_column`.

2024-05-14 16:08 UTC, kdumontnu requested changes
We should also update the `Part Number` output column to include the manufacturer if the user specifies one of the `mfr` + `mpn` options or add another column with manufacturer. Same thing for `No results found for CSRN2512FK50L0` - lets include the whole query.

It looks like because of the option type it just omits the manufacturer if the manufacturer is null (doesn't match). I think if we're using mpn it should error if we can't find `bom_manufacturer_column`.

2024-05-20 14:33 UTC, kdumontnu requested changes
I still think it's unintuitive that if a user sets `search_strategy: ..._mfr` and doesn't input `bom_manufacturer_column` that it will search with an empty string.

I think the following should occur:
- If one of the `_mfr` search options is set without a manufacturer column set it should error w/ "bom_manufacturer_column is required for mpn_sku_mfr and mpn_exact_mfr search strategies"
- If the other two search options are set and bom_manufacturer_column is set we should error with "bom_manufacturer_column is not used for default and mpn_exact search strategy."

2024-05-20 14:33 UTC, kdumontnu commented on action.yml
> +      The Cofactr search strategy. Can be: default, mpn_sku_mfr, mpn_exact, mpn_exact_mfr. Defaults
```suggestion
      The Cofactr search strategy. Can be: default (mpn), mpn_sku_mfr, mpn_exact, mpn_exact_mfr. Defaults
```

2024-05-20 14:33 UTC, kdumontnu commented on action.yml
> +      to 'mpn_sku_mfr'.
```suggestion
      to 'mpn_sku_mfr'. See Cofactr API documentation for more information on search strategies.
```

2024-05-20 16:52 UTC, jtran commented
> I still think it's unintuitive that if a user sets `search_strategy: ..._mfr` and doesn't input `bom_manufacturer_column` that it will search with an empty string.

That's not how the PR currently works. `bom_manufacturer_column` has a default value of "Manufacturer". So it will include the manufacturer value if it's not the empty string. It's currently not possible to not set a manufacturer. You can empty `bom_manufacturer_column` out to empty string, but that will error out because of the above requested changes https://github.com/AllSpiceIO/cofactr-cogs/pull/6#pullrequestreview-2055848882.

> * If one of the `_mfr` search options is set without a manufacturer column set it should error w/ "bom_manufacturer_column is required for mpn_sku_mfr and mpn_exact_mfr search strategies"

I assume you mean a "manufacturer value", not a "manufacturer column". That's not how the Cofactr API works. Even for the `*_mfr` strategies, the manufacturer value in the query is optional. But we can enforce this as an additional constraint if you want.

>  * If the other two search options are set and bom_manufacturer_column is set we should error with "bom_manufacturer_column is not used for default and mpn_exact search strategy."

As it currently is, `bom_manufacturer_column` has a default value of "Manufacturer". So to do what you're asking, we would either need to remove the default or they would have to use `bom_manufacturer_column: ''` to unset the `bom_manufacturer_column`, and then we'd need to handle that.

I think it would be better to inspect the search strategy, and if it's `mpn_exact`, then omit the manufacturer value from the query regardless of whether it's configured.

2024-05-21 15:05 UTC, kdumontnu requested changes
I'm running some test actions, and it's still quite difficult to understand what is happening when we run a report. It's unclear to me what's being searched and what values are returned. I'm not sure the manufacturer values are even being sent to the API for my components.

Here are my suggestions:
- If `*_mfr` search option is set, we should include a column in the output csv with the manufacturer that was included in the search in addition to `Part Number`.
  - An alternative is that we include the exact search query, but I think that's more confusing for users.
- The API returns a component ID, right? We should include a column with the Cofactr ID that matches the query so that the user can look up the component
- The `Warning: No results found` still doesn't appear to return the manufacturer when I set `search_strategy: mpn_sku_mfr` I get responses like `Warning: No results found for , NCV8402ADDR2G` (not including the manufacturer).
- I think we should get rid of the default for`bom_part_manufacturer_column`. That way, if they supply a value for `bom_part_manufacturer_column` but are using a search method that doesn't use manufacturer (eg. default or mpn_exact), we can throw an error. I see this as being a big point of confusion. 
  - We COULD remove defaults for all `bom_*_column` values. The names of the columns are likely to vary so much that I'm not sure having a default here really helps much.

2024-05-21 18:18 UTC, jtran commented
> * If `*_mfr` search option is set, we should include a column in the output csv with the manufacturer that was included in the search in addition to `Part Number`.

> * The `Warning: No results found` still doesn't appear to return the manufacturer when I set `search_strategy: mpn_sku_mfr` I get responses like `Warning: No results found for , NCV8402ADDR2G` (not including the manufacturer).

We do both of these things. I was concerned when I saw your repo switch from the commit hash to the branch name that you were using the wrong version of this. Your output above reinforces that this is likely the case.

When you reference a branch as in `uses: https://hub.allspice.io/Actions/cofactr-cogs@jt/search-strategy`, you're getting the old cached version of the branch. In the Action output, in the "Set up job" step, you can see output that looks like this:

```
  cloning https://hub.allspice.io/Actions/cofactr-cogs to /root/.cache/act/https---hub.allspice.io-Actions-cofactr-cogs@912649b5ac918837a957a777d30bb1eeedb09a8b
```

That commit hash doesn't exist anymore in any repo as far as I can tell. I was wondering if there's a way, as a user, to clear and/or update the cache, but I haven't found it yet.

2024-05-21 19:22 UTC, jtran commented
This issue seem related to the caching problem: https://github.com/nektos/act/issues/1785.

2024-05-23 20:32 UTC, kdumontnu requested changes
I'm running into an issue while testing:
```
Found prices for 72 parts
Traceback (most recent call last):
  File "/entrypoint.py", line 264, in <module>
    main()
  File "/entrypoint.py", line 225, in main
    largest_breakpoint_less_than_qty = max(
                                       ^^^^
ValueError: max() iterable argument is empty
```

2024-05-23 20:32 UTC, kdumontnu commented on entrypoint.py
> +            "Search strategy requires manufacturer, but no BOM manufacturer column was provided"
```suggestion
            "Search strategy requires manufacturer, but no BOM manufacturer column was provided. Please set bom_manufacturer_column."
```

2024-05-23 21:11 UTC, shrik450 commented on entrypoint.py
>  from argparse import ArgumentParser
A few notes:

- I feel like this file is getting complex enough to be split into two. I think having one file for arg parsing and main, and another for the logic would be a good idea. This isn't necessary, so feel free to keep it as-is.
- I would prefer `search_strategy` to be an enum instead of a string. Apart from standard benefits like typing, knowing exactly what values are allowed etc, this could also lead to a "cleaner" refactor for `query_needs_manufacturer` etc. Like:

  ```py

  class SearchStrategy(Enum):
      FUZZY = "fuzzy"
      # ...

      def query_needs_manufacturer(self) -> bool:
          # ...
  ```

  The other advantage of this approach is that it better validates the input and fails fast if the user inputs an incorrect value.

2024-05-23 21:11 UTC, shrik450 commented on entrypoint.py
> +        manufacturer = part[manufacturer_column] if use_mfr else ""
I think it makes more sense to omit this column if the column hasn't been specified.

2024-05-23 21:15 UTC, jtran commented on entrypoint.py
>  from argparse import ArgumentParser
I kind of thought that if Cofactr ever added a new search strategy, and it was just a string that we passed through, users could start using it without waiting for us to update the action, which we would need to do for an enum.

2024-05-23 21:45 UTC, shrik450 commented on entrypoint.py
>  from argparse import ArgumentParser
That's fair. I still think we should have some kind of warning/validation for the types, as if someone is typing them in they could make a typo. If we want to allow values we don't expect, we can warn them about it in the logs to make it clear.

2024-05-23 21:55 UTC, jtran commented on entrypoint.py
>  from argparse import ArgumentParser
I can change it to an enum. It's unlikely they'll add new strategies, and if they do, it will be infrequently.

2024-05-23 22:24 UTC, jtran commented on entrypoint.py
>  from argparse import ArgumentParser
> * I feel like this file is getting complex enough to be split into two. I think having one file for arg parsing and main, and another for the logic would be a good idea. This isn't necessary, so feel free to keep it as-is.

To me, it's not that it needs to be split in two as much as there should be tests. Right now, we're testing it by running it in an action in another repo. But there's no assertions about what the results should actually be.

Having tests would also inform the design in terms of how to split it up into multiple functions.

I could add tests in this PR. I thought it was out of scope and that the action as a whole is still in great flux where tests would be wasted effort as we change things around. But this PR might've actually gone faster if we had tests.

2024-05-24 22:46 UTC, kdumontnu approved these changes
💯 thanks for getting this together!

2024-05-28 18:12 UTC, shrik450 approved these changes
I think this PR is good to go as-is, but reading through the code made me think of two long-term design improvements we could make, especially if we want to test this code as well. Neither of these is necessary right now, and definitely isn't in the scope of this PR, but I wanted to note these down and maybe open an issue to pick these up later.

2024-05-28 18:12 UTC, shrik450 commented on cofactr_cogs/cli.py
> +            breakpoints = price_breakpoints(part_prices, quantity)
I think both `price_breakpoints` and this segment of code can be instance methods on `PartPrices`, which would also make them more testable. Not necessary short term.

2024-05-28 18:12 UTC, shrik450 commented on cofactr_cogs/api.py
> +    api_key = os.environ.get("COFACTR_API_KEY")
Getting the env vars for every call of this function seems unnecessary. I think this (and `search_strategy` in the function args) point to this function being a very procedural extraction that could be simplified with a little bit of OO design. E.g. we could make it an object we pass in the argument that makes the actual API call. Again, this would improve testability, and I think the other advantage here would be that we could swap out the object based on the API being used, so theoretically make this action also support digikey with the right args. This would be a very premature optimization right now.

2024-05-28 18:31 UTC, merged